# Generated by Django 4.1 on 2023-12-06 01:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='fname', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='lname', max_length=200),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhsNumber', models.CharField(default='0000000000', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('gender', models.CharField(default='gender', max_length=10)),
                ('birthDate', models.DateField(default=(2001, 3, 15))),
                ('disability', models.IntegerField(default=1)),
                ('contact', models.CharField(default='999', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
