# Generated by Django 4.1 on 2023-12-06 03:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombineUserPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('userType', models.IntegerField(default=-1)),
                ('firstName', models.CharField(default='fname', max_length=200)),
                ('lastName', models.CharField(default='lname', max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('nhsNumber', models.CharField(default='0000000000', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('gender', models.CharField(default='gender', max_length=10)),
                ('birthDate', models.DateField(default=(2001, 3, 15))),
                ('disability', models.IntegerField(default=1)),
                ('contact', models.CharField(default='999', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
