# Generated by Django 4.1 on 2023-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_combineuserpatient_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='fname', max_length=200),
        ),
    ]
