# Generated by Django 4.1 on 2023-12-06 15:20

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_lastname_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
