# Generated by Django 4.1 on 2023-12-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_firstname_combineuserpatient_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combineuserpatient',
            name='username',
        ),
    ]
