# Generated by Django 4.1 on 2023-12-06 21:36

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_combineuserpatient_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptRefID', models.CharField(default=api.models.generate_ref_id, max_length=8, unique=True)),
                ('apptDate', models.DateField(default=(2001, 3, 15))),
                ('apptTime', models.TimeField(default=(0, 0, 0))),
                ('apptEndTime', models.TimeField(default=(0, 0, 0))),
                ('addrPickUp', models.TextField(default='', max_length=1000)),
                ('addrAppt', models.TextField(default='', max_length=1000)),
                ('gpName', models.CharField(default='', max_length=200)),
                ('disability', models.IntegerField(default=-1)),
                ('escort', models.BooleanField(default=False)),
                ('notes', models.TextField(default='', max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
