# Generated by Django 4.1 on 2023-12-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_appointment_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patientID',
        ),
    ]
