# Generated by Django 4.1 on 2023-12-07 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_appointment_patientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
