# Generated by Django 4.1 on 2023-12-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_patient_id_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialReq',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
