# Generated by Django 4.1 on 2023-12-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_appointment_notes_alter_appointment_specialreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='neptsValid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
