# Generated by Django 4.1 on 2023-12-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_currentsituation_patient_currentcondition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combineuserpatient',
            old_name='currentSituation',
            new_name='currentCondition',
        ),
    ]
