# Generated by Django 4.1 on 2023-12-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_combineuserpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='combineuserpatient',
            name='password',
            field=models.CharField(default='password', max_length=200),
        ),
    ]
