# Generated by Django 4.1 on 2023-12-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_appointment_specialreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientID',
            field=models.BigIntegerField(default=-1),
        ),
    ]
