# Generated by Django 4.1 on 2023-12-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_appointment_notes_alter_appointment_specialreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialReq',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
