# Generated by Django 4.1 on 2023-12-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_combineuserpatient_currentsituation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='currentSituation',
            new_name='currentCondition',
        ),
    ]
