# Generated by Django 4.1 on 2024-01-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_staffaddappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apptRefID',
            new_name='refID',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.CreateModel(
            name='AppointmentPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
