# Generated by Django 4.1 on 2024-01-24 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_appointmentstaff_addrappt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addappointmentstaff',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='addappointmentstaff',
            name='nhsNumber',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='appointmentstaff',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='appointmentstaff',
            name='nhsNumber',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
