# Generated by Django 4.1 on 2024-04-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_addappointmentstaff_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=(2001, 3, 15), unique=True)),
                ('numPatient', models.IntegerField(default=-1)),
                ('addressList', models.TextField(default='', max_length=999999)),
                ('escortList', models.TextField(default='', max_length=999999)),
                ('schedule', models.TextField(default='', max_length=999999)),
                ('totalTime', models.FloatField(default=-1)),
                ('updateTime', models.DateTimeField(default=(2001, 3, 15, 15, 30))),
            ],
        ),
    ]
